name: learn-github-actions
on: [push]
jobs:
  go_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./go/gh-actions
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.0
      - name: Test go code
        run: |
          cd $GITHUB_WORKSPACE/go/gh-actions
          go test ./...
